insert into public.teams(code,name,flag,group_id) values
('MEX','México','🇲🇽','A'),
('RSA','Sudáfrica','🇿🇦','A'),
('KOR','Corea del Sur','🇰🇷','A'),
('CZE','Chequia','🇨🇿','A'),
('CAN','Canadá','🇨🇦','B'),
('BIH','Bosnia y Herzegovina','🇧🇦','B'),
('QAT','Qatar','🇶🇦','B'),
('SUI','Suiza','🇨🇭','B'),
('BRA','Brasil','🇧🇷','C'),
('MAR','Marruecos','🇲🇦','C'),
('HAI','Haití','🇭🇹','C'),
('SCO','Escocia','🏴','C'),
('USA','Estados Unidos','🇺🇸','D'),
('PAR','Paraguay','🇵🇾','D'),
('AUS','Australia','🇦🇺','D'),
('TUR','Turquía','🇹🇷','D'),
('GER','Alemania','🇩🇪','E'),
('CUW','Curazao','🇨🇼','E'),
('CIV','Costa de Marfil','🇨🇮','E'),
('ECU','Ecuador','🇪🇨','E'),
('NED','Países Bajos','🇳🇱','F'),
('JPN','Japón','🇯🇵','F'),
('SWE','Suecia','🇸🇪','F'),
('TUN','Túnez','🇹🇳','F'),
('BEL','Bélgica','🇧🇪','G'),
('EGY','Egipto','🇪🇬','G'),
('IRN','Irán','🇮🇷','G'),
('NZL','Nueva Zelanda','🇳🇿','G'),
('ESP','España','🇪🇸','H'),
('CPV','Cabo Verde','🇨🇻','H'),
('KSA','Arabia Saudita','🇸🇦','H'),
('URU','Uruguay','🇺🇾','H'),
('FRA','Francia','🇫🇷','I'),
('SEN','Senegal','🇸🇳','I'),
('IRQ','Irak','🇮🇶','I'),
('NOR','Noruega','🇳🇴','I'),
('ARG','Argentina','🇦🇷','J'),
('ALG','Argelia','🇩🇿','J'),
('AUT','Austria','🇦🇹','J'),
('JOR','Jordania','🇯🇴','J'),
('POR','Portugal','🇵🇹','K'),
('COD','RD Congo','🇨🇩','K'),
('UZB','Uzbekistán','🇺🇿','K'),
('COL','Colombia','🇨🇴','K'),
('ENG','Inglaterra','🏴','L'),
('CRO','Croacia','🇭🇷','L'),
('GHA','Ghana','🇬🇭','L'),
('PAN','Panamá','🇵🇦','L')
on conflict (code) do update set name=excluded.name, flag=excluded.flag, group_id=excluded.group_id;

insert into public.matches(id,group_id,round,match_no,home_team,away_team) values
('A1','A','GRUPOS','A-1','MEX','RSA'),
('A2','A','GRUPOS','A-2','KOR','CZE'),
('A3','A','GRUPOS','A-3','MEX','KOR'),
('A4','A','GRUPOS','A-4','CZE','RSA'),
('A5','A','GRUPOS','A-5','CZE','MEX'),
('A6','A','GRUPOS','A-6','RSA','KOR'),
('B1','B','GRUPOS','B-1','CAN','BIH'),
('B2','B','GRUPOS','B-2','QAT','SUI'),
('B3','B','GRUPOS','B-3','CAN','QAT'),
('B4','B','GRUPOS','B-4','SUI','BIH'),
('B5','B','GRUPOS','B-5','SUI','CAN'),
('B6','B','GRUPOS','B-6','BIH','QAT'),
('C1','C','GRUPOS','C-1','BRA','MAR'),
('C2','C','GRUPOS','C-2','HAI','SCO'),
('C3','C','GRUPOS','C-3','BRA','HAI'),
('C4','C','GRUPOS','C-4','SCO','MAR'),
('C5','C','GRUPOS','C-5','SCO','BRA'),
('C6','C','GRUPOS','C-6','MAR','HAI'),
('D1','D','GRUPOS','D-1','USA','PAR'),
('D2','D','GRUPOS','D-2','AUS','TUR'),
('D3','D','GRUPOS','D-3','USA','AUS'),
('D4','D','GRUPOS','D-4','TUR','PAR'),
('D5','D','GRUPOS','D-5','TUR','USA'),
('D6','D','GRUPOS','D-6','PAR','AUS'),
('E1','E','GRUPOS','E-1','GER','CUW'),
('E2','E','GRUPOS','E-2','CIV','ECU'),
('E3','E','GRUPOS','E-3','GER','CIV'),
('E4','E','GRUPOS','E-4','ECU','CUW'),
('E5','E','GRUPOS','E-5','ECU','GER'),
('E6','E','GRUPOS','E-6','CUW','CIV'),
('F1','F','GRUPOS','F-1','NED','JPN'),
('F2','F','GRUPOS','F-2','SWE','TUN'),
('F3','F','GRUPOS','F-3','NED','SWE'),
('F4','F','GRUPOS','F-4','TUN','JPN'),
('F5','F','GRUPOS','F-5','TUN','NED'),
('F6','F','GRUPOS','F-6','JPN','SWE'),
('G1','G','GRUPOS','G-1','BEL','EGY'),
('G2','G','GRUPOS','G-2','IRN','NZL'),
('G3','G','GRUPOS','G-3','BEL','IRN'),
('G4','G','GRUPOS','G-4','NZL','EGY'),
('G5','G','GRUPOS','G-5','NZL','BEL'),
('G6','G','GRUPOS','G-6','EGY','IRN'),
('H1','H','GRUPOS','H-1','ESP','CPV'),
('H2','H','GRUPOS','H-2','KSA','URU'),
('H3','H','GRUPOS','H-3','ESP','KSA'),
('H4','H','GRUPOS','H-4','URU','CPV'),
('H5','H','GRUPOS','H-5','URU','ESP'),
('H6','H','GRUPOS','H-6','CPV','KSA'),
('I1','I','GRUPOS','I-1','FRA','SEN'),
('I2','I','GRUPOS','I-2','IRQ','NOR'),
('I3','I','GRUPOS','I-3','FRA','IRQ'),
('I4','I','GRUPOS','I-4','NOR','SEN'),
('I5','I','GRUPOS','I-5','NOR','FRA'),
('I6','I','GRUPOS','I-6','SEN','IRQ'),
('J1','J','GRUPOS','J-1','ARG','ALG'),
('J2','J','GRUPOS','J-2','AUT','JOR'),
('J3','J','GRUPOS','J-3','ARG','AUT'),
('J4','J','GRUPOS','J-4','JOR','ALG'),
('J5','J','GRUPOS','J-5','JOR','ARG'),
('J6','J','GRUPOS','J-6','ALG','AUT'),
('K1','K','GRUPOS','K-1','POR','COD'),
('K2','K','GRUPOS','K-2','UZB','COL'),
('K3','K','GRUPOS','K-3','POR','UZB'),
('K4','K','GRUPOS','K-4','COL','COD'),
('K5','K','GRUPOS','K-5','COL','POR'),
('K6','K','GRUPOS','K-6','COD','UZB'),
('L1','L','GRUPOS','L-1','ENG','CRO'),
('L2','L','GRUPOS','L-2','GHA','PAN'),
('L3','L','GRUPOS','L-3','ENG','GHA'),
('L4','L','GRUPOS','L-4','PAN','CRO'),
('L5','L','GRUPOS','L-5','PAN','ENG'),
('L6','L','GRUPOS','L-6','CRO','GHA')
on conflict (id) do update set group_id=excluded.group_id, round=excluded.round, match_no=excluded.match_no, home_team=excluded.home_team, away_team=excluded.away_team;
